import { StatusBar, StyleSheet } from 'react-native';
export const itemStyles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#bcbcbc',
  },
  name: {
    fontSize: 18,
    fontWeight: 'bold',
    flexWrap: 'wrap',
    width: 150,
  },
  left: {
    flexDirection: 'row',
  },
  right: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  type: {
    marginRight: 4,
    justifyContent: 'center',
  },
  nameContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    width: 150,
  },
  capacity: {
    flexDirection: 'row',
    marginVertical: 4,
    width: 35,
    height: 35,
    borderRadius: 50,
    backgroundColor: 'darkred',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.8,
    borderWidth: 1,
    borderColor: 'black',
    borderStyle: 'solid',
  },
  capacityNumber: {
    flexDirection: 'row',
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  clan: {
    flexDirection: 'row',
    marginLeft: 14,
    marginRight: 14,
    width: 35,
    maxWidth: 35,
    height: 35,
    maxHeight: 35,
  },
  discipline: {
    flex: 1,
    flexWrap: 'wrap',
    flexDirection: 'row',
  },
  disciplineLibrary: {
    maxWidth: 35,
    width: 35,
  },
  cost: {
    width: 35,
    maxWidth: 35,
    height: 35,
    maxHeight: 35,
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
});
